// Single source of truth for the Arcatext terms of use text.
// Rendered both in the homepage About modal (about.tsx) and on the /terms page.
export function TermsOfUseContent() {
  return (
    <div className="space-y-4 text-sm text-gray-600 leading-relaxed">
      <p className="font-medium text-secondary">Operated by Adalithic LLC</p>
      <p>Last Updated: July 2, 2026</p>
      <p>
        These Terms of Use ("Terms") are a legal agreement between you and Adalithic LLC
        ("Adalithic," "we," "us," or "our"), the operator of Arcatext. Arcatext is an AI-assisted
        custom keyboard and language application that helps users write, translate, reword, reverse
        translate, clarify meaning, find synonyms, improve grammar, and better understand messages
        across languages. Arcatext may be provided through a mobile app, a custom keyboard
        extension, a website, and related services.
      </p>
      <p>
        By downloading, accessing, or using Arcatext, you agree to be bound by these Terms and by
        our Privacy Policy. If you do not agree to these Terms, do not use Arcatext.
      </p>

      <div className="bg-primary/5 border border-primary/20 p-4 rounded-lg">
        <h3 className="font-semibold text-secondary mb-2">Plain-English summary</h3>
        <p className="mb-2">
          This summary is provided for your convenience only. It is not a complete statement of
          these Terms, and if there is any conflict between this summary and the full Terms below,
          the full Terms control.
        </p>
        <ul className="list-disc list-outside pl-5 space-y-2">
          <li>Arcatext uses artificial intelligence to translate, reword, and analyze text.</li>
          <li>
            AI can make mistakes. Translations and rewordings may be inaccurate, incomplete,
            misleading, offensive, culturally wrong, or inappropriate for the context.
          </li>
          <li>
            You are responsible for reviewing any output before you use it, send it, or rely on it.
          </li>
          <li>
            Arcatext is not a substitute for a professional translator, attorney, doctor, financial
            advisor, immigration advisor, or other qualified professional.
          </li>
          <li>
            For anything important or high-stakes, have the output reviewed by a qualified human
            before you rely on it.
          </li>
        </ul>
      </div>

      <h3 className="font-semibold text-secondary pt-2">1. Who We Are</h3>
      <p>Arcatext is operated by Adalithic LLC.</p>
      <p>You can reach us at:</p>
      <p>
        Email: arcatextapp@gmail.com
        <br />
        Website: https://adalithic.com/
      </p>

      <h3 className="font-semibold text-secondary pt-2">2. Description of the Service</h3>
      <p>
        Arcatext is an AI-assisted custom keyboard and language application. Its features may
        include translation, rewording, reverse translation, grammar assistance, synonym
        suggestions, meaning clarification, and language-learning tools.
      </p>
      <p>
        Arcatext's output is generated by automated systems and third-party AI providers. It is not
        produced or reviewed by a human translator or professional reviewer. We may add, remove,
        change, limit, or modify features at any time, and we may update, suspend, or discontinue
        parts of the service.
      </p>

      <h3 className="font-semibold text-secondary pt-2">3. Eligibility and Minors</h3>
      <p>
        To use Arcatext, you must be able to form a binding contract with Adalithic LLC, or use
        Arcatext with the permission and supervision of a parent or legal guardian who agrees to
        these Terms on your behalf.
      </p>
      <p>
        Arcatext is not intended for children under 13. If you are under 13, you may not use
        Arcatext unless your parent, legal guardian, school, or authorized educational institution
        has approved your use in a manner permitted by applicable law. You agree to comply with all
        applicable laws when using Arcatext.
      </p>

      <h3 className="font-semibold text-secondary pt-2">
        4. AI Output, Translation Accuracy, and User Responsibility
      </h3>
      <p>
        Arcatext produces machine-generated language output. While we work to make Arcatext useful
        and reliable, automated translation and language tools can and do make errors. Output may
        be incorrect, inaccurate, incomplete, outdated, misleading, confusing, culturally
        inappropriate, or offensive.
      </p>
      <p>Among other things, Arcatext's output may misstate or alter:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Names</li>
        <li>Dates</li>
        <li>Numbers</li>
        <li>Addresses</li>
        <li>Prices</li>
        <li>Measurements</li>
        <li>Legal terms</li>
        <li>Medical terms</li>
        <li>Idioms and slang</li>
        <li>Cultural context</li>
        <li>Tone, formality, and intent</li>
      </ul>
      <p className="font-medium">
        Adalithic LLC does not take responsibility for any incorrect, inaccurate, misleading, or
        confusing translations or other output produced by Arcatext, sent in any context for any
        purpose.
      </p>
      <p>
        You are solely responsible for reviewing, verifying, and deciding whether to use or send
        any translation or other output before you rely on it, send it to another person, share it
        with a client or third party, or otherwise act on it. To the maximum extent permitted by
        law, Adalithic LLC is not responsible for any decisions, actions, messages, losses,
        misunderstandings, or other consequences resulting from your reliance on Arcatext's output.
      </p>
      <p>
        Arcatext is not a substitute for a professional human translator, interpreter, attorney,
        physician, financial advisor, immigration advisor, or other qualified professional. For
        important or high-stakes communications — including business, legal, medical, financial,
        safety, immigration, official, academic, and emergency matters — you should obtain
        independent review from a qualified human professional before relying on Arcatext's output.
      </p>

      <h3 className="font-semibold text-secondary pt-2">5. Your Responsibilities</h3>
      <p>When you use Arcatext, you agree that:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>
          You are responsible for the text you submit and for any output you choose to use or send.
        </li>
        <li>
          You are responsible for checking the recipient, context, tone, and meaning before sending
          any message that Arcatext generates or modifies.
        </li>
        <li>
          You will not use Arcatext to type or submit passwords, payment card numbers, security
          codes, or other highly sensitive information.
        </li>
        <li>
          You have the rights necessary to submit any text you provide, and your submissions do not
          violate any law or third-party rights.
        </li>
        <li>
          You are responsible for maintaining the confidentiality of any account credentials you
          use.
        </li>
      </ul>

      <h3 className="font-semibold text-secondary pt-2">6. User Content and License</h3>
      <p>
        "User Content" means the text, messages, prompts, pasted content, translations,
        corrections, preferences, feedback, and other content you submit to or generate through
        Arcatext. You retain ownership of the text you submit.
      </p>
      <p>
        You grant Adalithic LLC a limited, non-exclusive, worldwide, royalty-free license to host,
        process, transmit, reproduce, modify, and display the text you submit solely as necessary
        to provide, maintain, secure, troubleshoot, improve, and support Arcatext, including by
        transmitting text to the third-party service providers described in our Privacy Policy. Any
        use of your content to improve Arcatext's language features is governed by our Privacy
        Policy.
      </p>
      <p>
        Subject to these Terms, you may use Arcatext output for your lawful personal or internal
        business purposes. You are responsible for reviewing the output and ensuring your use does
        not violate any law or third-party rights.
      </p>

      <h3 className="font-semibold text-secondary pt-2">7. Privacy and AI Providers</h3>
      <p>
        Your use of Arcatext is also governed by our Privacy Policy, available at
        https://adalithic.com/privacy, which explains how we process information. If there is a
        conflict between these Terms and the Privacy Policy regarding the collection, use, storage,
        sharing, deletion, or retention of personal information, the Privacy Policy controls for
        those privacy matters.
      </p>
      <p>
        Arcatext uses third-party service providers to help provide the service, including AI model
        providers, cloud hosting providers, storage providers, analytics providers, authentication
        providers, customer support tools, and payment processors. These providers may process
        information as described in our Privacy Policy, and their handling of data is also governed
        by their own terms and policies.
      </p>

      <h3 className="font-semibold text-secondary pt-2">8. Acceptable Use</h3>
      <p>You agree not to use Arcatext to:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Violate any applicable law or regulation</li>
        <li>Infringe the intellectual property, privacy, or other rights of any person or entity</li>
        <li>Harass, threaten, abuse, defame, or otherwise harm others</li>
        <li>Impersonate another person or deceive recipients about your identity or intent</li>
        <li>Send spam or mass unsolicited messages</li>
        <li>Facilitate fraud, scams, phishing, or social engineering</li>
        <li>Exploit, sexualize, or harm minors</li>
        <li>Conduct illegal surveillance or unauthorized monitoring</li>
        <li>Bypass usage limits or security features</li>
        <li>Interfere with, overload, scrape, or disrupt the service or its systems</li>
        <li>
          Reverse engineer, decompile, or attempt to extract source code, except where permitted by
          law
        </li>
        <li>
          Attempt to extract prompts, model behavior, API keys, non-public system information, or
          security information
        </li>
        <li>
          Develop a competing product or build datasets in violation of these Terms or applicable
          law
        </li>
      </ul>

      <h3 className="font-semibold text-secondary pt-2">
        9. Subscriptions, Billing, Cancellation, and Refunds
      </h3>
      <p>
        Arcatext may offer paid subscriptions or in-app purchases. If you purchase a subscription
        through Apple's App Store, Google Play, or another platform, your purchase, renewal,
        cancellation, and refund rights are handled by that platform and may be subject to that
        platform's terms.
      </p>
      <p>
        Subscriptions automatically renew unless canceled before the end of the current billing
        period. Deleting the app does not cancel your subscription. You must cancel through the
        platform account settings where you purchased the subscription. If you cancel, you may
        continue to access paid features until the end of the current billing period, unless the
        platform provides otherwise. Where supported, you may restore prior purchases through the
        platform where you bought them.
      </p>
      <p>
        Fees are non-refundable except as required by law or as provided by the platform through
        which you purchased. Arcatext may change pricing or available plans from time to time,
        subject to applicable law and platform rules.
      </p>

      <h3 className="font-semibold text-secondary pt-2">10. App Store and Platform Terms</h3>
      <p>
        If you download Arcatext through Apple's App Store, your use is also subject to Apple's
        Licensed Application End User License Agreement (the standard Apple EULA), unless Adalithic
        LLC provides a custom end user license agreement through App Store Connect. To the extent of
        any conflict between these Terms and the applicable Apple terms with respect to your use on
        Apple-branded devices, the applicable Apple terms will govern that conflict.
      </p>
      <p>
        Apple is not responsible for Arcatext or its content and, except as required by applicable
        law, has no obligation to provide maintenance or support for Arcatext. Apple and its
        subsidiaries are third-party beneficiaries of these Terms as they relate to your use of
        Arcatext on Apple-branded devices, and Apple may enforce these Terms against you as a
        third-party beneficiary.
      </p>
      <p>
        If you download Arcatext through Google Play or another platform, your use may also be
        subject to that platform's terms and policies.
      </p>

      <h3 className="font-semibold text-secondary pt-2">11. Intellectual Property</h3>
      <p>
        Arcatext — including its software, design, branding, user interface, features,
        documentation, and, where applicable, its prompts and configurations, together with content
        provided by Adalithic LLC — is owned by Adalithic LLC or its licensors and is protected by
        intellectual property laws.
      </p>
      <p>
        Subject to these Terms, we grant you a limited, personal, non-exclusive, non-transferable,
        revocable license to use Arcatext. You may not copy, modify, distribute, sell, lease,
        sublicense, or otherwise exploit Arcatext except as permitted by these Terms or applicable
        law. You retain ownership of the text you submit, as described in the User Content section
        above.
      </p>

      <h3 className="font-semibold text-secondary pt-2">12. Disclaimer of Warranties</h3>
      <p>
        Arcatext is provided on an "as is" and "as available" basis, without warranties of any
        kind, whether express, implied, or statutory. To the fullest extent permitted by law,
        Adalithic LLC disclaims all warranties, including any implied warranties of merchantability,
        fitness for a particular purpose, accuracy, and non-infringement, and any warranties arising
        out of course of dealing or usage of trade.
      </p>
      <p>
        We do not warrant that Arcatext will preserve the meaning, tone, cultural context,
        formality, or intent of any text, or that the service will be uninterrupted, secure, or
        error-free, or that any output will be accurate, reliable, or suitable for your intended
        purpose.
      </p>

      <h3 className="font-semibold text-secondary pt-2">13. Limitation of Liability</h3>
      <p>
        To the fullest extent permitted by applicable law, in no event will Adalithic LLC, its
        members, officers, employees, contractors, or service providers be liable for any indirect,
        incidental, special, consequential, exemplary, or punitive damages, or for any loss of
        profits, revenue, data, goodwill, business, reputation, or opportunities, or for any
        misunderstandings caused by translation or other output errors, arising out of or related to
        your use of, or inability to use, Arcatext — whether based on warranty, contract, tort
        (including negligence), statute, or any other legal theory, and whether or not Adalithic LLC
        has been advised of the possibility of such damages.
      </p>
      <p>
        To the fullest extent permitted by applicable law, the total aggregate liability of
        Adalithic LLC arising out of or relating to these Terms or your use of Arcatext will not
        exceed the greater of (a) the total amount you paid to Adalithic LLC or through the
        applicable platform for Arcatext in the twelve (12) months preceding the event giving rise
        to the claim, or (b) one hundred U.S. dollars (US$100).
      </p>
      <p>Nothing in these Terms limits liability that cannot be limited under applicable law.</p>

      <h3 className="font-semibold text-secondary pt-2">14. Indemnification</h3>
      <p>
        To the extent permitted by applicable law, you agree to indemnify, defend, and hold harmless
        Adalithic LLC and its members, officers, employees, contractors, and service providers from
        and against any claims, liabilities, damages, losses, and expenses, including reasonable
        attorneys' fees, arising out of or related to your use of Arcatext, your reliance on or
        distribution of any output, your User Content, your violation of these Terms, or your
        violation of any law or the rights of any third party.
      </p>

      <h3 className="font-semibold text-secondary pt-2">15. Termination</h3>
      <p>
        You may stop using Arcatext at any time by removing it from your keyboard list or
        uninstalling the app. We may suspend, limit, or terminate your access to Arcatext to protect
        the service, comply with law, prevent abuse, address security issues, enforce usage limits,
        or respond to violations of these Terms.
      </p>
      <p>
        Termination does not automatically entitle you to a refund unless required by law or
        platform policy. Provisions that by their nature should survive termination — including the
        disclaimers, limitations of liability, indemnification, intellectual property, User Content
        and license, governing law and dispute provisions, and any outstanding payment obligations —
        will survive.
      </p>

      <h3 className="font-semibold text-secondary pt-2">16. Governing Law</h3>
      <p>
        These Terms are governed by the laws of the State of Delaware, without regard to its
        conflict-of-laws principles, except where applicable consumer protection law requires
        otherwise. Subject to any mandatory consumer protection rights available to you in your
        place of residence, and except for disputes subject to arbitration under Section 17, you
        agree that any dispute arising out of or relating to these Terms or your use of Arcatext
        will be subject to the exclusive jurisdiction of the state and federal courts located in
        Delaware. The Federal Arbitration Act governs the interpretation and enforcement of the
        arbitration provisions in Section 17.
      </p>

      <h3 className="font-semibold text-secondary pt-2">
        17. Dispute Resolution; Binding Arbitration and Class-Action Waiver
      </h3>
      <p className="font-medium">
        PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS. IT REQUIRES THAT MOST
        DISPUTES BETWEEN YOU AND ADALITHIC LLC BE RESOLVED THROUGH INDIVIDUAL, BINDING ARBITRATION
        RATHER THAN IN COURT, AND IT WAIVES YOUR RIGHT TO A JURY TRIAL AND YOUR RIGHT TO PARTICIPATE
        IN A CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION. YOU MAY OPT OUT OF ARBITRATION WITHIN 30
        DAYS AS DESCRIBED BELOW.
      </p>
      <p>
        <span className="font-medium">A. Agreement to Arbitrate.</span> You and Adalithic LLC agree
        that any dispute, claim, or controversy arising out of or relating to these Terms, the
        Privacy Policy, Arcatext, or your use of Arcatext — whether based in contract, tort,
        statute, fraud, misrepresentation, or any other legal theory, and whether arising before or
        during the term of these Terms — will be resolved by binding, individual arbitration, except
        as expressly provided in this Section 17. This agreement to arbitrate is intended to be
        broadly interpreted, evidences a transaction involving interstate commerce, and is governed
        by the Federal Arbitration Act (the "FAA").
      </p>
      <p>
        <span className="font-medium">B. Informal Resolution First.</span> Before starting an
        arbitration, you and Adalithic LLC agree to try to resolve the dispute informally for at
        least 60 days. To begin, the party raising the dispute must send a written Notice of Dispute
        to the other. Your Notice of Dispute must be sent to arcatextapp@gmail.com and must include
        your name, the email address associated with your account, a description of the dispute, and
        the specific relief you seek. If the dispute is not resolved within 60 days after a complete
        Notice of Dispute is received, either party may begin an arbitration. This informal
        resolution process is a condition precedent to starting an arbitration.
      </p>
      <p>
        <span className="font-medium">C. Arbitration Procedure.</span> The arbitration will be
        administered by the American Arbitration Association (the "AAA") under its Consumer
        Arbitration Rules then in effect, as modified by these Terms. If the AAA is unavailable or
        unwilling to administer the arbitration consistent with these Terms, you and Adalithic LLC
        will select an alternative arbitration provider. The arbitration will be conducted by a
        single neutral arbitrator. At your election, the arbitration may be conducted by telephone
        or videoconference, based solely on written submissions, or in person in the county (or
        equivalent) of your residence. The arbitrator's award is final and binding, and judgment on
        the award may be entered in any court of competent jurisdiction.
      </p>
      <p>
        <span className="font-medium">D. Arbitrator's Authority.</span> The arbitrator has exclusive
        authority to resolve any dispute relating to the interpretation, applicability,
        enforceability, or formation of this agreement to arbitrate, including any claim that all or
        any part of it is void or voidable. However, a court of competent jurisdiction — and not an
        arbitrator — has exclusive authority to resolve any dispute about the enforceability,
        validity, or scope of the Class-Action Waiver in paragraph E. The arbitrator may award the
        same damages and individual relief that a court could award under applicable law, but only
        in favor of the individual party seeking relief and only to the extent necessary to provide
        relief on that party's individual claim.
      </p>
      <p>
        <span className="font-medium">E. Class-Action Waiver.</span>{" "}
        <span className="font-medium">
          YOU AND ADALITHIC LLC AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN
          INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS,
          COLLECTIVE, CONSOLIDATED, PRIVATE ATTORNEY GENERAL, OR OTHER REPRESENTATIVE PROCEEDING.
        </span>{" "}
        Unless both you and Adalithic LLC agree otherwise in writing, the arbitrator may not
        consolidate or join more than one person's claims and may not otherwise preside over any
        form of a class, collective, or representative proceeding, except as provided in the
        Coordinated and Mass Arbitration paragraph below.
      </p>
      <p>
        <span className="font-medium">F. Coordinated and Mass Arbitration.</span> If 25 or more
        Notices of Dispute or demands for arbitration raising similar claims are asserted against
        Adalithic LLC by or with the assistance of the same or coordinated counsel, or in a
        coordinated manner, you and Adalithic LLC agree that the demands will be administered in
        staged batches of up to 50 demands at a time (plus, as needed, a final batch of fewer than
        50), in accordance with the AAA's mass-arbitration or supplementary procedures then in
        effect. A single arbitrator will preside over each batch. After a reasonable number of
        batches are resolved, the parties will engage in a single mediation and, informed by the
        outcomes of the arbitrated batches, will attempt in good faith to resolve the remaining
        demands. Filing and administrative fees for later batches will not become due until earlier
        batches are resolved. This paragraph is intended to promote the efficient and fair
        resolution of large numbers of similar demands and does not create a class or representative
        proceeding.
      </p>
      <p>
        <span className="font-medium">G. Fees and Costs.</span> Payment of filing, administrative,
        and arbitrator fees will be governed by the applicable AAA rules, except that Adalithic LLC
        will pay or reimburse those fees to the extent required by the AAA Consumer Arbitration
        Rules or applicable law. Each party is otherwise responsible for its own attorneys' fees and
        costs, unless the arbitrator determines that a claim was frivolous or brought for an
        improper purpose, or unless applicable law provides otherwise.
      </p>
      <p>
        <span className="font-medium">H. Jury-Trial Waiver.</span> To the extent any dispute is
        permitted to proceed in court rather than arbitration, you and Adalithic LLC each knowingly
        and voluntarily waive any right to a trial by jury.
      </p>
      <p>
        <span className="font-medium">I. Small-Claims Exception.</span> Notwithstanding the
        foregoing, either party may bring an individual claim in a small-claims court of competent
        jurisdiction if the claim qualifies and remains an individual action in that court.
      </p>
      <p>
        <span className="font-medium">J. 30-Day Right to Opt Out.</span> You may opt out of this
        agreement to arbitrate (Section 17) within 30 days after you first accept these Terms. To
        opt out, send written notice to arcatextapp@gmail.com with the subject line "Arbitration
        Opt-Out," including your name, the email address associated with your account, and a clear
        statement that you wish to opt out of arbitration. Opting out applies only to this Section
        17 and does not affect any other part of these Terms; if you opt out, disputes will be
        resolved in court as provided in the Governing Law section, and the Jury-Trial Waiver and
        Class-Action Waiver will continue to apply to the extent permitted by applicable law.
      </p>
      <p>
        <span className="font-medium">K. Severability.</span> If the Class-Action Waiver in
        paragraph E is found to be unenforceable as to a particular claim or request for relief,
        then that claim or request for relief (and only that claim or request) will be severed and
        brought in a court of competent jurisdiction as provided in the Governing Law section, while
        all remaining claims will continue to be resolved in arbitration. If the prohibition on
        class or representative arbitration is found to be unenforceable, then the entire agreement
        to arbitrate in this Section 17 will be null and void as to the affected claim, which will
        instead proceed in court. Except as stated in this paragraph, if any other provision of this
        Section 17 is found to be unenforceable, it will be severed and the remainder of this
        Section 17 will remain in effect.
      </p>
      <p>
        <span className="font-medium">L. Changes to This Section; Survival.</span> If Adalithic LLC
        makes a material change to this Section 17 after you accept these Terms, you may reject the
        change by sending written notice to arcatextapp@gmail.com within 30 days of the change, in
        which case the most recent version of this Section 17 that you accepted before the change
        will govern. This Section 17 survives termination of these Terms and your use of Arcatext.
      </p>

      <h3 className="font-semibold text-secondary pt-2">18. Changes to These Terms</h3>
      <p>
        We may update these Terms from time to time to reflect changes in our app, technology,
        service providers, legal obligations, or business practices. When we update the Terms, we
        will revise the "Last Updated" date above. If changes are significant, we may provide
        additional notice through the app, website, or other appropriate methods.
      </p>
      <p>
        Your continued use of Arcatext after the updated Terms take effect constitutes acceptance of
        the updated Terms. If you do not agree to the updated Terms, you must stop using Arcatext.
      </p>

      <h3 className="font-semibold text-secondary pt-2">19. Contact Us</h3>
      <p>If you have questions about these Terms, contact:</p>
      <p>
        Adalithic LLC
        <br />
        Arcatext Support
        <br />
        Email: arcatextapp@gmail.com
        <br />
        Website: https://adalithic.com/
      </p>
    </div>
  );
}
