// Single source of truth for the Arcatext terms of use text.
// Rendered both in the homepage About modal (about.tsx) and on the /terms page.
export function TermsOfUseContent() {
  return (
    <div className="space-y-4 text-sm text-gray-600 leading-relaxed">
      <p className="font-medium text-secondary">Operated by Adalithic LLC</p>
      <p>Last Updated: July 2, 2026</p>
      <p>
        These Terms of Use ("Terms") are a legal agreement between you and Adalithic LLC
        ("Adalithic," "we," "us," or "our") and govern your access to and use of Arcatext, including
        our mobile app, custom keyboard extension, website, and related language tools and services.
      </p>
      <p>
        By downloading, accessing, enabling, creating an account for, purchasing a subscription for,
        tapping to accept, or using Arcatext, you agree to these Terms and to our Privacy Policy. If
        you do not agree to these Terms, do not use Arcatext.
      </p>

      <div className="bg-primary/5 border border-primary/20 p-4 rounded-lg">
        <h3 className="font-semibold text-secondary mb-2">Plain-English summary</h3>
        <p className="mb-2">
          This summary is provided for convenience only. If there is any conflict between this
          summary and the full Terms below, the full Terms control.
        </p>
        <ul className="list-disc list-outside pl-5 space-y-2">
          <li>
            Arcatext uses AI to help translate, reword, correct, and explain text across languages.
          </li>
          <li>
            AI can make mistakes. Translations and other outputs may be inaccurate, incomplete,
            misleading, confusing, culturally inappropriate, offensive, or different from what you
            intended.
          </li>
          <li>
            You are responsible for reviewing any output before you rely on it, send it, share it,
            or act on it — especially for business, legal, medical, financial, immigration, safety,
            academic, official, or emergency-related communications.
          </li>
          <li>
            Arcatext is not a substitute for a professional human translator, interpreter, attorney,
            physician, financial advisor, immigration advisor, emergency service, or other qualified
            professional. For anything important, have the output reviewed by a qualified human.
          </li>
          <li>
            These Terms require most disputes to be resolved by individual arbitration and waive
            class actions and jury trials. You may opt out of arbitration within 30 days as
            described in the Dispute Resolution section.
          </li>
        </ul>
      </div>

      <h3 className="font-semibold text-secondary pt-2">1. Who We Are</h3>
      <p>
        Arcatext is operated by Adalithic LLC, a limited liability company organized under the laws
        of the State of Delaware.
      </p>
      <p>For questions about these Terms, contact us at:</p>
      <p>
        Adalithic LLC
        <br />
        Arcatext Support
        <br />
        Email: arcatextapp@gmail.com
        <br />
        Website: https://adalithic.com/
      </p>

      <h3 className="font-semibold text-secondary pt-2">2. Description of the Service</h3>
      <p>
        Arcatext is an AI-assisted custom keyboard and language application that helps users write,
        translate, reword, reverse translate, clarify meaning, improve grammar, view synonym
        suggestions, and better understand messages across languages.
      </p>
      <p>
        Arcatext's features rely on automated systems and third-party service providers, including
        AI model providers. Arcatext output is generated by machine and is not reviewed by a human
        translator, interpreter, attorney, physician, financial advisor, immigration advisor,
        emergency service, or other professional before being shown to you.
      </p>
      <p>
        We may add, remove, limit, suspend, replace, or modify features from time to time. We may
        also change the third-party providers, models, systems, or technical methods used to provide
        Arcatext.
      </p>

      <h3 className="font-semibold text-secondary pt-2">3. Eligibility</h3>
      <p>
        Arcatext is not intended for children under 13. If you are under 13, do not use Arcatext
        unless your use is expressly authorized by a parent, legal guardian, school, or authorized
        educational institution in a manner permitted by applicable law and consistent with our
        Privacy Policy.
      </p>
      <p>
        If you are under the age of majority where you live, you may use Arcatext only with
        permission from a parent or legal guardian.
      </p>
      <p>
        By using Arcatext, you represent that you are able to form a binding contract with Adalithic
        or that you have the required permission to use Arcatext. If Arcatext is used by a school,
        organization, or business, additional agreements or policies may apply.
      </p>

      <h3 className="font-semibold text-secondary pt-2">
        4. AI Output, Translation Accuracy, and User Responsibility
      </h3>
      <p>
        Arcatext produces machine-generated language output. While we work to make Arcatext useful
        and reliable, automated translation and language tools can and do make errors.
      </p>
      <p>
        Arcatext output may be incorrect, inaccurate, incomplete, outdated, misleading, confusing,
        contextually inappropriate, culturally inappropriate, offensive, or unsuitable for your
        intended purpose. Output may misinterpret, alter, or omit meaning, tone, formality, idioms,
        slang, names, dates, numbers, addresses, prices, measurements, medical terms, legal terms,
        immigration terms, cultural references, or intent.
      </p>
      <p className="font-medium">
        Adalithic LLC does not take responsibility for any incorrect, inaccurate, misleading, or
        confusing translations or other output produced by Arcatext, sent in any context for any
        purpose.
      </p>
      <p>
        You are solely responsible for reviewing, verifying, and deciding whether to use, rely on,
        send, publish, or share any translation or other output generated by Arcatext. You are
        responsible for checking the recipient, context, tone, meaning, and appropriateness of any
        message before sending it.
      </p>
      <p>
        To the maximum extent permitted by law, Adalithic is not responsible for decisions, actions,
        messages, misunderstandings, losses, damages, or consequences that result from your use of,
        reliance on, or sharing of Arcatext output.
      </p>
      <p>
        Arcatext is not a substitute for a professional human translator, interpreter, attorney,
        physician, financial advisor, immigration advisor, emergency service, or other qualified
        professional. For communications where accuracy is important — including business, legal,
        medical, financial, safety, immigration, academic, official, or emergency matters — you
        should obtain independent review from a qualified human professional before relying on
        Arcatext output.
      </p>
      <p>
        Nothing in these Terms is intended to exclude or limit any responsibility that cannot be
        excluded or limited under applicable law.
      </p>

      <h3 className="font-semibold text-secondary pt-2">5. Your Responsibilities</h3>
      <p>When you use Arcatext, you agree that:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>
          You are responsible for the text you submit and for any output you choose to use, send,
          share, publish, or rely on.
        </li>
        <li>
          You will independently verify the accuracy, meaning, tone, and appropriateness of any
          output before relying on it.
        </li>
        <li>
          You will not use Arcatext to type, submit, translate, or process passwords, payment card
          numbers, security codes, private keys, government identification numbers, or other highly
          sensitive information.
        </li>
        <li>You will comply with all applicable laws and regulations when using Arcatext.</li>
        <li>
          You are responsible for maintaining the confidentiality of any account credentials you
          use.
        </li>
        <li>
          You are responsible for ensuring that you have the rights and permissions necessary to
          submit any text or content to Arcatext.
        </li>
      </ul>

      <h3 className="font-semibold text-secondary pt-2">6. Submitted Content and Output</h3>
      <p>
        "Submitted Content" means text, messages, prompts, pasted content, feedback, preferences,
        and other content that you submit to Arcatext.
      </p>
      <p>
        "Output" means translations, corrections, rewordings, explanations, synonym suggestions,
        grammar suggestions, and other content generated or returned by Arcatext.
      </p>
      <p>
        You retain ownership of your Submitted Content. Adalithic does not claim ownership of the
        text or other content you submit to Arcatext.
      </p>
      <p>
        You grant Adalithic a limited, non-exclusive, worldwide, royalty-free license to host,
        process, transmit, reproduce, modify, and display Submitted Content solely as necessary to
        provide, maintain, secure, troubleshoot, improve, and support Arcatext, including by
        transmitting Submitted Content to the third-party service providers described in our Privacy
        Policy. Any use of Submitted Content for improvement, analytics, retention, storage,
        deletion, or similar purposes is subject to our Privacy Policy.
      </p>
      <p>
        Subject to these Terms, you may use Output for your lawful personal or internal business
        purposes. You are responsible for reviewing Output and ensuring that your use of Output does
        not violate any law, contract, privacy right, intellectual property right, or other
        third-party right.
      </p>
      <p>
        Our collection, use, storage, retention, deletion, and sharing of information is described
        in our Privacy Policy.
      </p>

      <h3 className="font-semibold text-secondary pt-2">7. Privacy</h3>
      <p>
        Your use of Arcatext is also governed by our Privacy Policy, which explains how we collect,
        use, store, disclose, retain, and delete information. The Privacy Policy is available at
        https://adalithic.com/privacy.
      </p>
      <p>
        If there is a conflict between these Terms and the Privacy Policy regarding the collection,
        use, storage, disclosure, retention, or deletion of personal information, the Privacy Policy
        controls for those privacy matters.
      </p>
      <p>
        Arcatext uses third-party service providers to help provide the service, including AI model
        providers, cloud hosting providers, storage providers, analytics providers, authentication
        providers, customer support tools, payment processors, and app marketplace platforms. These
        providers may process information as described in our Privacy Policy.
      </p>

      <h3 className="font-semibold text-secondary pt-2">8. Acceptable Use</h3>
      <p>You agree not to use Arcatext to:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Violate any applicable law or regulation.</li>
        <li>
          Infringe, misappropriate, or violate the intellectual property, privacy, publicity, or
          other rights of any person or entity.
        </li>
        <li>
          Transmit unlawful, harassing, defamatory, abusive, threatening, harmful, hateful,
          deceptive, or otherwise objectionable content.
        </li>
        <li>Impersonate another person or misrepresent your identity, affiliation, intent, or authority.</li>
        <li>
          Deceive recipients or facilitate fraud, scams, phishing, social engineering, or other
          harmful conduct.
        </li>
        <li>Send spam, mass unsolicited messages, or abusive multilingual campaigns.</li>
        <li>Exploit, sexualize, endanger, or harm minors.</li>
        <li>
          Engage in illegal surveillance, unauthorized monitoring, or unauthorized collection of
          information.
        </li>
        <li>
          Attempt to gain unauthorized access to Arcatext, its systems, its providers, or other
          users' accounts.
        </li>
        <li>Interfere with, disrupt, overload, scrape, crawl, or abuse Arcatext or its underlying systems.</li>
        <li>
          Bypass or attempt to bypass usage limits, payment requirements, security features, or
          access controls.
        </li>
        <li>
          Reverse engineer, decompile, disassemble, or attempt to extract the source code of
          Arcatext, except to the extent permitted by law.
        </li>
        <li>
          Attempt to extract prompts, model behavior, API keys, security information, non-public
          system information, or confidential information.
        </li>
        <li>
          Develop a competing product, train a competing system, or build datasets in violation of
          these Terms or applicable law.
        </li>
        <li>Misuse, overload, or abuse Arcatext or its underlying AI providers.</li>
      </ul>
      <p>
        We may suspend, limit, or terminate access to Arcatext if we believe you have violated these
        Terms, created risk for Adalithic, harmed another person, abused the service, or used
        Arcatext in a way that could create legal, security, operational, or reputational risk.
      </p>

      <h3 className="font-semibold text-secondary pt-2">9. Subscriptions, Billing, and Payments</h3>
      <p>Arcatext may offer paid subscriptions, in-app purchases, or other paid features.</p>
      <p>
        If you purchase a subscription or paid feature through Apple's App Store, Google Play, or
        another third-party platform, your purchase, billing, renewal, cancellation, and refund
        rights are handled by that platform and may also be subject to that platform's terms and
        policies.
      </p>
      <p>
        Subscriptions automatically renew unless canceled before the end of the current billing
        period. Deleting Arcatext, disabling the keyboard, or uninstalling the app does not cancel
        your subscription. You must cancel through the platform account settings where you purchased
        the subscription.
      </p>
      <p>
        If you cancel a subscription, you may continue to access paid features until the end of the
        current billing period, unless the platform provides otherwise.
      </p>
      <p>
        If Arcatext offers a free trial or promotional period, the subscription may automatically
        convert to a paid subscription at the end of the trial unless you cancel before the trial
        ends, as described at the time of purchase.
      </p>
      <p>
        Fees are non-refundable except as required by law or as provided by the platform through
        which you purchased. Arcatext may change pricing, plans, usage limits, or paid features from
        time to time, subject to applicable law and platform rules. Where required, we or the
        applicable platform will provide notice of price changes. Where supported by the platform,
        Arcatext may provide a way to restore prior purchases.
      </p>
      <p>
        Subscription price, billing period, renewal terms, trial terms, features included, and
        cancellation instructions are disclosed by the applicable app marketplace and/or at the
        point of purchase before you subscribe. You should review those terms carefully before
        purchasing. If any purchase screen, platform disclosure, or legally required disclosure
        provides additional rights or terms that apply to your purchase, those terms apply to that
        purchase.
      </p>
      <p>
        If Adalithic offers subscriptions directly outside an app marketplace, we will provide the
        automatic-renewal terms, cancellation policy, price, renewal frequency, and other legally
        required disclosures before you subscribe. For directly billed subscriptions, we will
        provide a reasonably accessible online cancellation method as required by applicable law.
      </p>

      <h3 className="font-semibold text-secondary pt-2">
        10. App Store, Google Play, and Platform Terms
      </h3>
      <p>
        If you download Arcatext through Apple's App Store, Google Play, or another app marketplace,
        your use of Arcatext may also be subject to that platform's terms, policies, and license
        agreements.
      </p>
      <p>
        If you download Arcatext through Apple's App Store, Apple's Licensed Application End User
        License Agreement, also known as the standard Apple EULA, may apply unless Adalithic provides
        a custom license agreement through App Store Connect. Apple is not responsible for Arcatext
        or its content and, except as required by applicable law, has no obligation to provide
        maintenance or support for Arcatext.
      </p>
      <p>
        As between you and Adalithic, Adalithic is responsible for Arcatext and its content,
        maintenance and support, product claims, warranty claims to the extent not disclaimed,
        intellectual-property claims, and claims arising under consumer protection, privacy, or
        similar laws, except as otherwise provided in these Terms and to the maximum extent
        permitted by applicable law.
      </p>
      <p>
        Apple and its subsidiaries are third-party beneficiaries of these Terms as they relate to
        your use of Arcatext on Apple-branded devices, and Apple may enforce these Terms against you
        as a third-party beneficiary.
      </p>
      <p>
        You represent that you are not located in a country or region subject to a U.S. government
        embargo and are not listed on any U.S. government list of prohibited or restricted parties.
        You also agree to comply with applicable third-party terms when using Arcatext, including any
        wireless data service, app marketplace, or device terms that apply to your use.
      </p>
      <p>
        If you download Arcatext through Google Play, your purchase and use may also be subject to
        Google Play's applicable terms and policies. To the extent there is a conflict between these
        Terms and the applicable platform terms, the platform terms may control for issues related
        to billing, refunds, platform account management, and app marketplace requirements.
      </p>

      <h3 className="font-semibold text-secondary pt-2">11. Intellectual Property</h3>
      <p>
        Arcatext — including its software, design, user interface, features, branding, logos,
        documentation, configurations, prompts, systems, and content provided by Adalithic — is
        owned by Adalithic or its licensors and is protected by intellectual property and other
        laws.
      </p>
      <p>
        Subject to these Terms, we grant you a limited, personal, non-exclusive, non-transferable,
        non-sublicensable, revocable license to use Arcatext for your own personal or internal
        business purposes. You may not copy, modify, distribute, sell, lease, sublicense, publicly
        display, publicly perform, create derivative works from, or otherwise exploit Arcatext
        except as expressly permitted by these Terms or applicable law.
      </p>
      <p>
        You retain ownership of the text you submit, as described in the Submitted Content and
        Output section above.
      </p>
      <p>All rights not expressly granted to you are reserved by Adalithic and its licensors.</p>

      <h3 className="font-semibold text-secondary pt-2">12. Third-Party Services</h3>
      <p>
        Arcatext relies on third-party service providers to provide, secure, analyze, improve, and
        support the service. These providers may include AI model providers, cloud hosting
        providers, storage providers, analytics providers, authentication providers, customer
        support tools, payment processors, and app marketplace platforms.
      </p>
      <p>
        Adalithic is not responsible for the acts, omissions, systems, outages, policies, or
        independent conduct of third-party providers. However, our use of third-party providers to
        process information is described in our Privacy Policy. Third-party services may change from
        time to time, and Arcatext may be unavailable or limited if a third-party provider is
        unavailable, restricted, discontinued, or changed.
      </p>

      <h3 className="font-semibold text-secondary pt-2">13. Service Availability and Changes</h3>
      <p>
        Arcatext is provided as an evolving service. We may modify, suspend, limit, replace, or
        discontinue any part of Arcatext at any time.
      </p>
      <p>
        We do not guarantee that Arcatext will always be available, uninterrupted, secure,
        error-free, or compatible with every device, operating system, app, keyboard environment,
        language, or third-party service. We may impose usage limits, rate limits, feature limits,
        or technical restrictions to protect Arcatext, manage costs, prevent abuse, comply with law,
        or maintain service quality.
      </p>

      <h3 className="font-semibold text-secondary pt-2">14. Disclaimer of Warranties</h3>
      <p>
        Arcatext is provided on an "as is" and "as available" basis, without warranties of any kind,
        whether express, implied, statutory, or otherwise.
      </p>
      <p>
        To the fullest extent permitted by law, Adalithic disclaims all warranties, including
        implied warranties of merchantability, fitness for a particular purpose, accuracy,
        non-infringement, quiet enjoyment, and any warranties arising out of course of dealing or
        usage of trade.
      </p>
      <p>
        We do not warrant that Arcatext will be uninterrupted, secure, error-free, accurate,
        reliable, available, or suitable for your intended purpose, or that Arcatext will preserve
        the meaning, tone, formality, cultural context, or intent of any text. You understand and
        agree that you use Arcatext and any output at your own risk.
      </p>

      <h3 className="font-semibold text-secondary pt-2">15. Limitation of Liability</h3>
      <p>
        To the fullest extent permitted by applicable law, Adalithic LLC, its members, officers,
        employees, contractors, service providers, licensors, and affiliates will not be liable for
        any indirect, incidental, special, consequential, exemplary, punitive, or enhanced damages,
        or for any loss of profits, revenue, data, goodwill, business, reputation, opportunities, or
        other intangible losses, arising out of or related to your use of, or inability to use,
        Arcatext. This limitation applies to damages arising from Arcatext output, including
        translations or other output that are incorrect, inaccurate, incomplete, misleading,
        confusing, offensive, culturally inappropriate, or unsuitable for your intended purpose.
      </p>
      <p>
        To the fullest extent permitted by applicable law, the total aggregate liability of
        Adalithic arising out of or relating to these Terms or your use of Arcatext will not exceed
        the greater of (a) the total amount you paid to Adalithic for Arcatext in the twelve (12)
        months preceding the event giving rise to the claim, or (b) one hundred U.S. dollars
        (US$100).
      </p>
      <p>
        The limitations in this section apply whether a claim is based on warranty, contract, tort,
        negligence, statute, strict liability, or any other legal theory, and whether or not
        Adalithic has been advised of the possibility of such damages. Some jurisdictions do not
        allow the exclusion or limitation of certain warranties or liabilities; in those
        jurisdictions, the exclusions and limitations above apply only to the maximum extent
        permitted by law. Nothing in these Terms limits liability that cannot be limited under
        applicable law.
      </p>

      <h3 className="font-semibold text-secondary pt-2">16. Indemnification</h3>
      <p>
        To the extent permitted by applicable law, you agree to indemnify, defend, and hold harmless
        Adalithic LLC, its members, officers, employees, contractors, service providers, licensors,
        and affiliates from and against any claims, liabilities, damages, losses, and expenses,
        including reasonable attorneys' fees, arising out of or related to:
      </p>
      <ul className="list-disc pl-6 space-y-1">
        <li>your use of Arcatext;</li>
        <li>your Submitted Content;</li>
        <li>
          your reliance on, use of, sending of, publication of, or distribution of Arcatext output;
        </li>
        <li>your violation of these Terms;</li>
        <li>your violation of applicable law; or</li>
        <li>your violation of any rights of another person or entity.</li>
      </ul>
      <p>
        We reserve the right to control the defense of any matter subject to indemnification, and
        you agree to cooperate with our defense of those claims.
      </p>

      <h3 className="font-semibold text-secondary pt-2">17. Termination</h3>
      <p>
        You may stop using Arcatext at any time by removing it from your keyboard list, disabling
        it, or uninstalling the app.
      </p>
      <p>
        We may suspend, limit, or terminate your access to Arcatext at any time, with or without
        notice where permitted by law, including if we believe that you have violated these Terms,
        created risk for Adalithic or others, misused the service, failed to pay applicable fees,
        violated applicable law, or used Arcatext in a way that may create legal, security,
        operational, or reputational risk. Where practicable, we will provide notice, but we may act
        without notice when necessary to protect Arcatext, users, Adalithic, third-party providers,
        or legal compliance.
      </p>
      <p>
        We may also suspend, limit, or terminate Arcatext or any feature if we discontinue the
        service, modify our business, experience technical issues, lose access to third-party
        providers, or need to comply with law.
      </p>
      <p>
        Termination of access does not automatically entitle you to a refund unless required by law
        or by the platform through which you purchased. Sections that by their nature should survive
        termination will survive, including sections related to Submitted Content, Output,
        intellectual property, privacy, disclaimers, limitations of liability, indemnification,
        governing law, dispute resolution and arbitration, and payment obligations.
      </p>

      <h3 className="font-semibold text-secondary pt-2">18. Governing Law</h3>
      <p>
        These Terms are governed by the laws of the State of Delaware, without regard to its
        conflict-of-laws principles, except where applicable consumer protection law requires
        otherwise. Subject to any rights you may have under applicable consumer protection laws, and
        except for disputes subject to arbitration under Section 19, any dispute arising out of or
        relating to these Terms or your use of Arcatext will be brought in the state or federal
        courts located in Delaware, and you consent to the personal jurisdiction of those courts.
        The Federal Arbitration Act governs the interpretation and enforcement of the arbitration
        provisions in Section 19. Nothing in this section limits rights that you may have under
        applicable law that cannot be waived by contract.
      </p>

      <h3 className="font-semibold text-secondary pt-2">
        19. Dispute Resolution; Binding Arbitration and Class-Action Waiver
      </h3>
      <p className="font-medium">
        PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR LEGAL RIGHTS. IT REQUIRES THAT MOST
        DISPUTES BETWEEN YOU AND ADALITHIC LLC BE RESOLVED THROUGH INDIVIDUAL, BINDING ARBITRATION
        RATHER THAN IN COURT, AND IT WAIVES YOUR RIGHT TO A JURY TRIAL AND YOUR RIGHT TO PARTICIPATE
        IN A CLASS, COLLECTIVE, OR REPRESENTATIVE ACTION. YOU MAY OPT OUT OF ARBITRATION WITHIN 30
        DAYS AS DESCRIBED BELOW.
      </p>
      <p>
        <span className="font-medium">A. Agreement to Arbitrate.</span> You and Adalithic LLC agree
        that any dispute, claim, or controversy arising out of or relating to these Terms, the
        Privacy Policy, Arcatext, or your use of Arcatext — whether based in contract, tort,
        statute, fraud, misrepresentation, or any other legal theory, and whether arising before or
        during the term of these Terms — will be resolved by binding, individual arbitration, except
        as expressly provided in this Section 19. This agreement to arbitrate is intended to be
        broadly interpreted, evidences a transaction involving interstate commerce, and is governed
        by the Federal Arbitration Act.
      </p>
      <p>
        <span className="font-medium">B. Informal Resolution First.</span> Before starting an
        arbitration, you and Adalithic LLC agree to try to resolve the dispute informally for at
        least 60 days. To begin, the party raising the dispute must send a written Notice of Dispute
        to the other. Your Notice of Dispute must be sent to arcatextapp@gmail.com and must include,
        to the extent reasonably available, your name, the email address associated with your
        account, a description of the dispute, and the specific relief you seek. If the dispute is
        not resolved within 60 days after a complete Notice of Dispute is received, either party may
        begin an arbitration. This informal resolution process is a condition precedent to starting
        an arbitration.
      </p>
      <p>
        <span className="font-medium">C. Arbitration Procedure.</span> The arbitration will be
        administered by the American Arbitration Association ("AAA") under its Consumer Arbitration
        Rules then in effect, as modified by these Terms. If the AAA is unavailable or unwilling to
        administer the arbitration consistent with these Terms, you and Adalithic LLC will select an
        alternative arbitration provider. If you and Adalithic LLC cannot agree on an alternative
        provider, either party may ask a court of competent jurisdiction to appoint an arbitration
        provider or arbitrator consistent with the Federal Arbitration Act. The arbitration will be
        conducted by a single neutral arbitrator. At your election, the arbitration may be conducted
        by telephone or videoconference, based solely on written submissions, or in person in the
        county or equivalent jurisdiction of your residence. The arbitrator's award is final and
        binding, and judgment on the award may be entered in any court of competent jurisdiction.
      </p>
      <p>
        <span className="font-medium">D. Arbitrator's Authority.</span> The arbitrator has exclusive
        authority to resolve any dispute relating to the interpretation, applicability,
        enforceability, or formation of this agreement to arbitrate, including any claim that all or
        any part of it is void or voidable. However, a court of competent jurisdiction — and not an
        arbitrator — has exclusive authority to resolve any dispute about the enforceability,
        validity, or scope of the Class-Action Waiver in paragraph E.
      </p>
      <p>
        The arbitrator may award the same damages and individual relief that a court could award
        under applicable law, but only in favor of the individual party seeking relief and only to
        the extent necessary to provide relief on that party's individual claim. Nothing in these
        Terms prevents either party from seeking public injunctive relief where applicable law
        provides that such relief cannot be waived or limited by contract. Any dispute about whether
        a claim seeks public injunctive relief that cannot be waived will be decided by a court of
        competent jurisdiction to the extent required by applicable law.
      </p>
      <p>
        <span className="font-medium">E. Class-Action Waiver.</span>{" "}
        <span className="font-medium">
          YOU AND ADALITHIC LLC AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN AN
          INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS,
          COLLECTIVE, CONSOLIDATED, PRIVATE ATTORNEY GENERAL, OR OTHER REPRESENTATIVE PROCEEDING.
        </span>{" "}
        Unless both you and Adalithic LLC agree otherwise in writing, the arbitrator may not
        consolidate or join more than one person's claims and may not otherwise preside over any
        form of a class, collective, or representative proceeding, except as provided in the
        Coordinated and Mass Arbitration paragraph below. These Terms govern consumer and user
        access to Arcatext and are not intended to govern employment-related claims unless expressly
        agreed in a separate written agreement.
      </p>
      <p>
        <span className="font-medium">F. Coordinated and Mass Arbitration.</span> If 25 or more
        Notices of Dispute or demands for arbitration raising similar claims are asserted against
        Adalithic LLC by or with the assistance of the same or coordinated counsel, or in a
        coordinated manner, you and Adalithic LLC agree that the demands will be administered in
        staged batches of up to 50 demands at a time, plus, as needed, a final batch of fewer than
        50, in accordance with the AAA's mass-arbitration or supplementary procedures then in
        effect. A single arbitrator will preside over each batch. After a reasonable number of
        batches are resolved, the parties will engage in a single mediation and, informed by the
        outcomes of the arbitrated batches, will attempt in good faith to resolve the remaining
        demands. Filing and administrative fees for later batches will not become due until earlier
        batches are resolved. This paragraph is intended to promote the efficient and fair
        resolution of large numbers of similar demands and does not create a class, collective,
        consolidated, private attorney general, or representative proceeding.
      </p>
      <p>
        <span className="font-medium">G. Fees and Costs.</span> Payment of filing, administrative,
        and arbitrator fees will be governed by the applicable AAA rules, except that Adalithic LLC
        will pay or reimburse those fees to the extent required by the AAA Consumer Arbitration
        Rules or applicable law. Each party is otherwise responsible for its own attorneys' fees and
        costs, unless the arbitrator determines that a claim was frivolous or brought for an
        improper purpose, or unless applicable law provides otherwise.
      </p>
      <p>
        <span className="font-medium">H. Jury-Trial Waiver.</span> To the extent any dispute is
        permitted to proceed in court rather than arbitration, you and Adalithic LLC each knowingly
        and voluntarily waive any right to a trial by jury.
      </p>
      <p>
        <span className="font-medium">I. Small-Claims Exception.</span> Notwithstanding the
        foregoing, either party may bring an individual claim in a small-claims court of competent
        jurisdiction if the claim qualifies and remains an individual action in that court.
      </p>
      <p>
        <span className="font-medium">J. 30-Day Right to Opt Out.</span> You may opt out of this
        agreement to arbitrate (Section 19) within 30 days after you first accept these Terms. To
        opt out, send written notice to arcatextapp@gmail.com with the subject line "Arbitration
        Opt-Out," including your name, the email address associated with your account, and a clear
        statement that you wish to opt out of arbitration. Opting out applies only to this Section
        19 and does not affect any other part of these Terms. If you opt out, disputes will be
        resolved in court as provided in the Governing Law section, and the Jury-Trial Waiver and
        Class-Action Waiver will continue to apply to the extent permitted by applicable law.
      </p>
      <p>
        <span className="font-medium">K. Severability.</span> If the Class-Action Waiver in
        paragraph E is found to be unenforceable as to a particular claim or request for relief,
        then that claim or request for relief, and only that claim or request, will be severed and
        brought in a court of competent jurisdiction as provided in the Governing Law section, while
        all remaining claims will continue to be resolved in arbitration.
      </p>
      <p>
        If a court determines that a claim for public injunctive relief cannot be required to
        proceed in individual arbitration or cannot be waived under applicable law, that claim for
        public injunctive relief will be severed and heard in court, while all other arbitrable
        claims will remain subject to arbitration to the maximum extent permitted by law.
      </p>
      <p>
        If the prohibition on class or representative arbitration is found to be unenforceable, then
        the entire agreement to arbitrate in this Section 19 will be null and void as to the
        affected claim, which will instead proceed in court. Except as stated in this paragraph, if
        any other provision of this Section 19 is found to be unenforceable, it will be severed and
        the remainder of this Section 19 will remain in effect.
      </p>
      <p>
        <span className="font-medium">L. Changes to This Section; Survival.</span> If Adalithic LLC
        makes a material change to this Section 19 after you accept these Terms, you may reject the
        change by sending written notice to arcatextapp@gmail.com within 30 days of the change, in
        which case the most recent version of this Section 19 that you accepted before the change
        will govern. This Section 19 survives termination of these Terms and your use of Arcatext.
      </p>

      <h3 className="font-semibold text-secondary pt-2">20. Changes to These Terms</h3>
      <p>
        We may update these Terms from time to time to reflect changes in Arcatext, technology,
        service providers, legal obligations, business practices, or user needs. When we update
        these Terms, we will revise the "Last Updated" date at the top. If changes are significant,
        we may provide additional notice through the app, website, email, or other appropriate
        methods.
      </p>
      <p>
        Your continued use of Arcatext after the updated Terms become effective means you accept the
        updated Terms. If you do not agree to the updated Terms, you must stop using Arcatext.
      </p>

      <h3 className="font-semibold text-secondary pt-2">21. Contact Us</h3>
      <p>If you have questions about these Terms, contact us at:</p>
      <p>
        Adalithic LLC
        <br />
        Arcatext Support
        <br />
        Email: arcatextapp@gmail.com
        <br />
        Website: https://adalithic.com/
      </p>

      <h3 className="font-semibold text-secondary pt-2">22. Notices</h3>
      <p>
        We may send you notices electronically, including by email to the address associated with
        your account, through in-app notifications, or by posting on our website or in the app. You
        consent to receive electronic communications from us in connection with these Terms and your
        use of Arcatext. Notices are effective when sent or posted.
      </p>

      <h3 className="font-semibold text-secondary pt-2">23. Entire Agreement</h3>
      <p>
        These Terms, together with our Privacy Policy and any other agreements or policies expressly
        incorporated by reference, constitute the entire agreement between you and Adalithic LLC
        concerning Arcatext and supersede all prior or contemporaneous agreements, representations,
        and understandings, whether written or oral. If any provision of these Terms is held to be
        invalid or unenforceable, the remaining provisions will remain in full force and effect.
      </p>
    </div>
  );
}
