// Single source of truth for the Arcatext terms of use text.
// Rendered both in the homepage About modal (about.tsx) and on the /terms page.
export function TermsOfUseContent() {
  return (
    <div className="space-y-4 text-sm text-gray-600 leading-relaxed">
      <p className="font-medium text-secondary">Operated by Adalithic LLC</p>
      <p>Last Updated: June 26, 2026</p>
      <p>
        These Terms of Use ("Terms") govern your access to and use of Arcatext, a custom keyboard
        and language application that helps users write, translate, reword, and better understand
        messages across languages. Arcatext is operated by Adalithic LLC ("Adalithic," "we," "us,"
        or "our").
      </p>
      <p>
        By downloading, accessing, or using Arcatext, you agree to be bound by these Terms. If you
        do not agree to these Terms, do not use Arcatext.
      </p>

      <h3 className="font-semibold text-secondary pt-2">1. Who We Are</h3>
      <p>Arcatext is operated by Adalithic LLC.</p>
      <p>For questions about these Terms, contact us at:</p>
      <p>
        Email: arcatextapp@gmail.com
        <br />
        Support Page: https://adalithic.com/
      </p>

      <h3 className="font-semibold text-secondary pt-2">2. Description of the Service</h3>
      <p>
        Arcatext provides AI-assisted language tools, which may include translation, rewording,
        reverse translation, synonym suggestions, grammar assistance, meaning clarification, and
        learning features. These features rely on automated systems and third-party AI service
        providers, and their output is generated by machine, not by a human translator or
        professional reviewer.
      </p>

      <h3 className="font-semibold text-secondary pt-2">3. Eligibility</h3>
      <p>
        Arcatext is a general audience application. If you are under the age of 13, you may use
        Arcatext only with the permission and supervision of a parent or legal guardian. By using
        Arcatext, you represent that you are able to form a binding contract with Adalithic LLC and
        that you will comply with these Terms.
      </p>

      <div className="bg-primary/5 border border-primary/20 p-4 rounded-lg">
        <h3 className="font-semibold text-secondary mb-2">In simple terms</h3>
        <ol className="list-decimal list-outside pl-5 space-y-2">
          <li>
            Arcatext uses AI to translate and reword text. AI can make mistakes, and translations
            may be incorrect, inaccurate, misleading, or confusing.
          </li>
          <li>
            You are responsible for reviewing any translation before you rely on it, send it, or
            act on it — especially in business, legal, medical, financial, or other important
            contexts.
          </li>
          <li>
            Adalithic LLC is not responsible for any outcome that results from a translation or
            other output you choose to use.
          </li>
          <li>
            For anything important, have the output reviewed by a qualified human translator or
            professional.
          </li>
        </ol>
      </div>

      <h3 className="font-semibold text-secondary pt-2">
        4. Translation Accuracy and No Responsibility for Output
      </h3>
      <p>
        Arcatext produces machine-generated language output. While we work to make Arcatext useful
        and reliable, automated translation and language tools can and do make errors. Output may
        be incorrect, inaccurate, incomplete, outdated, misleading, confusing, contextually
        inappropriate, or offensive, and it may misinterpret meaning, tone, formality, idioms,
        slang, names, numbers, or cultural context.
      </p>
      <p className="font-medium">
        Adalithic LLC does not take responsibility for any incorrect, inaccurate, misleading, or
        confusing translations or other output produced by Arcatext, sent in any context for any
        purpose.
      </p>
      <p>
        You are solely responsible for reviewing, verifying, and deciding whether to rely on any
        translation or other output before using it, sending it to another person, sharing it with
        a client or third party, or otherwise acting on it. You assume all risk arising from your
        use of Arcatext's output.
      </p>
      <p>
        Arcatext is not a substitute for a professional human translator, interpreter, attorney,
        physician, financial advisor, or other qualified professional. For communications where
        accuracy is important — including but not limited to business, legal, medical, financial,
        safety, immigration, or official matters — you should obtain independent review from a
        qualified human professional before relying on Arcatext's output.
      </p>

      <h3 className="font-semibold text-secondary pt-2">5. Your Responsibilities</h3>
      <p>When you use Arcatext, you agree that:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>You are responsible for the text you submit and for any output you choose to use or send.</li>
        <li>
          You will independently verify the accuracy and appropriateness of any output before
          relying on it.
        </li>
        <li>
          You will not use Arcatext to type or submit passwords, payment card numbers, security
          codes, or other highly sensitive information.
        </li>
        <li>You will comply with all applicable laws when using Arcatext.</li>
        <li>You are responsible for maintaining the confidentiality of any account credentials you use.</li>
      </ul>

      <h3 className="font-semibold text-secondary pt-2">6. Acceptable Use</h3>
      <p>You agree not to use Arcatext to:</p>
      <ul className="list-disc pl-6 space-y-1">
        <li>Violate any applicable law or regulation</li>
        <li>Infringe the intellectual property or other rights of any person or entity</li>
        <li>Transmit unlawful, harassing, defamatory, abusive, threatening, or harmful content</li>
        <li>Attempt to gain unauthorized access to, interfere with, or disrupt the app or its systems</li>
        <li>Reverse engineer, decompile, or attempt to extract the source code of the app, except as permitted by law</li>
        <li>Use the app to develop a competing product or to build datasets in violation of these Terms or applicable law</li>
        <li>Misuse, overload, or abuse the service or its underlying AI providers</li>
      </ul>

      <h3 className="font-semibold text-secondary pt-2">7. Disclaimer of Warranties</h3>
      <p>
        Arcatext is provided on an "as is" and "as available" basis, without warranties of any
        kind, whether express, implied, or statutory. To the fullest extent permitted by law,
        Adalithic LLC disclaims all warranties, including any implied warranties of
        merchantability, fitness for a particular purpose, accuracy, non-infringement, and any
        warranties arising out of course of dealing or usage of trade.
      </p>
      <p>
        We do not warrant that Arcatext will be uninterrupted, secure, error-free, or that any
        output will be accurate, reliable, or fit for your intended purpose.
      </p>

      <h3 className="font-semibold text-secondary pt-2">8. Limitation of Liability</h3>
      <p>
        To the fullest extent permitted by applicable law, in no event will Adalithic LLC, its
        members, officers, employees, contractors, or service providers be liable for any indirect,
        incidental, special, consequential, exemplary, or punitive damages, or for any loss of
        profits, revenue, data, goodwill, business, or reputation, arising out of or related to
        your use of, or inability to use, Arcatext or any output it produces — including any
        damages arising from a translation or other output that is incorrect, inaccurate,
        misleading, or confusing — whether based on warranty, contract, tort (including
        negligence), statute, or any other legal theory, and whether or not Adalithic LLC has been
        advised of the possibility of such damages.
      </p>
      <p>
        To the fullest extent permitted by applicable law, the total aggregate liability of
        Adalithic LLC arising out of or relating to these Terms or your use of Arcatext will not
        exceed the greater of (a) the total amount you paid to Adalithic LLC for Arcatext in the
        twelve (12) months preceding the event giving rise to the claim, or (b) twenty U.S. dollars
        (US$20).
      </p>
      <p>
        Some jurisdictions do not allow the exclusion or limitation of certain warranties or
        liabilities, so some of the above exclusions and limitations may not apply to you. In such
        cases, our liability is limited to the maximum extent permitted by law.
      </p>

      <h3 className="font-semibold text-secondary pt-2">9. Indemnification</h3>
      <p>
        You agree to indemnify, defend, and hold harmless Adalithic LLC and its members, officers,
        employees, contractors, and service providers from and against any claims, liabilities,
        damages, losses, and expenses, including reasonable attorneys' fees, arising out of or
        related to your use of Arcatext, your reliance on or distribution of any output, your
        violation of these Terms, or your violation of any law or the rights of any third party.
      </p>

      <h3 className="font-semibold text-secondary pt-2">10. Intellectual Property</h3>
      <p>
        Arcatext, including its software, design, branding, and content provided by Adalithic LLC,
        is owned by Adalithic LLC or its licensors and is protected by intellectual property laws.
        Subject to these Terms, we grant you a limited, personal, non-exclusive, non-transferable,
        revocable license to use Arcatext for your own personal or internal purposes. You retain
        ownership of the text you submit, and you are responsible for ensuring you have the rights
        necessary to submit that text.
      </p>

      <h3 className="font-semibold text-secondary pt-2">11. Third-Party Services</h3>
      <p>
        Arcatext relies on third-party service providers, including AI providers, hosting, storage,
        analytics, authentication, and payment processors, to provide its features. Your use of
        these features may also be subject to those providers' own terms and policies. Adalithic
        LLC is not responsible for the acts, omissions, output, or content of third-party
        providers.
      </p>

      <h3 className="font-semibold text-secondary pt-2">12. Subscriptions, Billing, and Payments</h3>
      <p>
        If Arcatext offers paid features, subscriptions, or in-app purchases, payment may be
        processed by third-party platform providers such as Apple's App Store or Google Play.
        Purchases, renewals, cancellations, and refunds may be governed by those platforms' rules
        in addition to these Terms. Unless required by law or stated otherwise, fees are
        non-refundable.
      </p>

      <h3 className="font-semibold text-secondary pt-2">13. Termination</h3>
      <p>
        You may stop using Arcatext at any time by removing it from your keyboard list or
        uninstalling the app. We may suspend or terminate your access to Arcatext at any time,
        with or without notice, if we believe you have violated these Terms or if we discontinue
        the service. Provisions that by their nature should survive termination — including the
        disclaimers, limitations of liability, and indemnification — will survive.
      </p>

      <h3 className="font-semibold text-secondary pt-2">14. Privacy</h3>
      <p>
        Your use of Arcatext is also governed by our Privacy Policy, which explains how we process
        information. By using Arcatext, you acknowledge the practices described in the Privacy
        Policy.
      </p>

      <h3 className="font-semibold text-secondary pt-2">15. Governing Law</h3>
      <p>
        These Terms are governed by the laws of the State in which Adalithic LLC is organized,
        without regard to its conflict-of-laws principles, except where applicable consumer
        protection law provides otherwise. Any dispute arising out of or relating to these Terms or
        your use of Arcatext will be subject to the jurisdiction of the courts located in that
        State, unless applicable law requires otherwise.
      </p>

      <h3 className="font-semibold text-secondary pt-2">16. Changes to These Terms</h3>
      <p>
        We may update these Terms from time to time to reflect changes in our app, technology,
        service providers, legal obligations, or business practices. When we update the Terms, we
        will revise the "Last Updated" date at the top. If changes are significant, we may provide
        additional notice through the app, website, or other appropriate methods. Your continued
        use of Arcatext after the Terms are updated constitutes acceptance of the updated Terms.
      </p>

      <h3 className="font-semibold text-secondary pt-2">17. Contact Us</h3>
      <p>If you have questions about these Terms, contact:</p>
      <p>
        Adalithic LLC
        <br />
        Arcatext Support
        <br />
        Email: arcatextapp@gmail.com
        <br />
        Support Page: https://adalithic.com/
      </p>
    </div>
  );
}
